apiVersion: cloudrun.gcp.upbound.io/v1beta2
kind: V2Service
metadata:
  name: test-service
spec:
  providerConfigRef:
    name: gcp-family-providerconfig
  forProvider:
    ingress: INGRESS_TRAFFIC_ALL
    location: europe-west1
    template:
      # IMPORTANT: We need to specify the service account so that we can
      # control its permissions. If the service account is not specified, the
      # service runs with the default compute engine account which lacks
      # permissions to operate on buckets
      serviceAccount: gcloud-functions@cf-on-k8s-wg.iam.gserviceaccount.com
      containers:
        - image: korifi/file-api:4
---
# Needed to make service available without authentication
apiVersion: cloudrun.gcp.upbound.io/v1beta2
kind: ServiceIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudrun/v1beta2/service
  labels:
    testing.upbound.io/example-name: cloudrun-service
  name: cloudrun-service
spec:
  providerConfigRef:
    name: gcp-family-providerconfig
  forProvider:
    location: europe-west1
    member: allUsers
    role: roles/run.invoker
    service: test-service
