apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositestorageeventinstances.syn.tools
  labels:
    service.syn.tools/id: storageevent-offering # uuidgen | tr '[:upper:]' '[:lower:]'
    service.syn.tools/name: storageevent
    service.syn.tools/updatable: 'false'
  annotations:
    service.syn.tools/description: Gcloud Storage Events
    service.syn.tools/metadata: |
      {
        "displayName": "Gcloud Storage Events"
      }
    service.syn.tools/tags: |
      ["trigger", "storage", "events", "gcloud"]
spec:
  group: syn.tools
  names:
    kind: CompositeStorageEventInstance
    plural: compositestorageeventinstances
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: "The service instance parameters"
                  properties:
                    eventHandlerImage:
                      type: string
                      description: "The image of the event handler function"
                    bucketName:
                      type: string
                      description: "The name of the source bucket"
                    parameters:
                      type: string
                      description: "The parameters to be passed to the event handler function in JSON format"
                  required: ["eventHandlerImage", "bucketName", "parameters"]

      referenceable: true
      served: true
      additionalPrinterColumns:
        - jsonPath: .metadata.labels['service\.syn\.tools/plan']
          name: Plan
          type: string
        - jsonPath: .metadata.labels['service\.syn\.tools/cluster']
          name: Cluster
          type: string
